from math import pi, atan2
from utils import linalg2_util as linalg
from robot_control.controllers.avoid_obstacles_controller import AvoidObstaclesController
from robot_control.controllers.go_to_goal_controller import GoToGoalController


class GTGAndAOController:
    """
    This class implements a controller that combines a Go-To-Goal (GTG) controller
    and an Avoid-Obstacle (AO) controller for a robot. The controller blends the heading
    vectors from both controllers with a user-defined weight to navigate towards a 
    goal while avoiding obstacles.

    **Attributes:**
    * supervisor (Webots.Supervisor): Reference to the Webots supervisor object for interacting with the robot simulator.
    * go_to_goal_controller (GoToGoalController): Instance of the GoToGoalController class.
    * avoid_obstacles_controller (AvoidObstaclesController): Instance of the AvoidObstaclesController class.
    * sensor_gains (list[float]): Weights for the AO controller based on sensor angle.
    * alpha (float): Weight for blending GTG and AO heading vectors (0 to 1).
    * kP (float): Proportional control gain.
    * kI (float): Integral control gain.
    * kD (float): Derivative control gain.
    * prev_time (float): Time of the previous control iteration.
    * prev_eP (float): Previous proportional error.
    * prev_eI (float): Previous integral error.
    * gtg_heading_vector (list[float]): Heading vector calculated by the GTG controller.
    * ao_heading_vector (list[float]): Heading vector calculated by the AO controller.
    * obstacle_vectors (list[list[float]]): List of obstacle vectors calculated by the AO controller.
    * blended_heading_vector (list[float]): Blended heading vector for robot movement.

    **Methods:**
    * __init__(self, supervisor): Constructor to initialize the controller.
    * update_heading(self): Updates the blended heading vector based on GTG and AO controllers.
    * execute(self): Calculates the desired robot velocity based on the blended heading vector.
    * _print_vars(self, eP, eI, eD, v, omega): Prints debugging information about control 
                                                variables (optional).
    """
    def __init__(self, supervisor):
        # bind the supervisor
        self.supervisor = supervisor

        # initialize controllers to blend
        self.go_to_goal_controller = GoToGoalController(supervisor)
        self.avoid_obstacles_controller = AvoidObstaclesController(supervisor)

        # sensor gains (weights)
        self.avoid_obstacles_controller.sensor_gains = [
            1.0 - ((0.4 * abs(p.theta)) / pi)
            for p in self.avoid_obstacles_controller.proximity_sensor_placements
        ]

        # blending factor
        # go-to-goal heading is given this much weight, avoid-obstacles is given the
        # remaining weight
        self.alpha = 0.1

        # control gains
        self.kP = 10.0
        self.kI = 0.0
        self.kD = 0.0

        # stored values - for computing next results
        self.prev_time = 0.0
        self.prev_eP = 0.0
        self.prev_eI = 0.0

        # key vectors and data (initialize to any non-zero vector)
        self.obstacle_vectors = [[1.0, 0.0]] * len(
            self.avoid_obstacles_controller.proximity_sensor_placements
        )
        self.ao_heading_vector = [1.0, 0.0]
        self.gtg_heading_vector = [1.0, 0.0]
        self.blended_heading_vector = [1.0, 0.0]

    def update_heading(self):
        # generate and store the vectors generated by the two controller types
        self.gtg_heading_vector = (
            self.go_to_goal_controller.calculate_gtg_heading_vector()
        )
        (
            self.ao_heading_vector,
            self.obstacle_vectors,
        ) = self.avoid_obstacles_controller.calculate_ao_heading_vector()

        # normalize the heading vectors
        self.gtg_heading_vector = linalg.unit(self.gtg_heading_vector)
        self.ao_heading_vector = linalg.unit(self.ao_heading_vector)

        # generate the blended vector
        self.blended_heading_vector = linalg.add(
            linalg.scale(self.gtg_heading_vector, self.alpha),
            linalg.scale(self.ao_heading_vector, 1.0 - self.alpha),
        )

    def execute(self):
        # calculate the time that has passed since the last control iteration
        current_time = self.supervisor.time()
        dt = current_time - self.prev_time

        # calculate the error terms
        theta_d = atan2(self.blended_heading_vector[1], self.blended_heading_vector[0])
        eP = theta_d
        eI = self.prev_eI + eP * dt
        eD = (eP - self.prev_eP) / dt

        # calculate angular velocity
        omega = self.kP * eP + self.kI * eI + self.kD * eD

        # calculate translational velocity
        # velocity is v_max when omega is 0,
        # drops rapidly to zero as |omega| rises
        v = self.supervisor.v_max() / (abs(omega) + 1) ** 1.5

        # store values for next control iteration
        self.prev_time = current_time
        self.prev_eP = eP
        self.prev_eI = eI

        self.supervisor.set_outputs(v, omega)

        # === FOR DEBUGGING ===
        # self._print_vars( eP, eI, eD, v, omega )

    def _print_vars(self, eP, eI, eD, v, omega):
        print("\n\n")
        print("==============")
        print("ERRORS:")
        print("eP: " + str(eP))
        print("eI: " + str(eI))
        print("eD: " + str(eD) + "\n")
        print("CONTROL COMPONENTS:")
        print("kP * eP = " + str(self.kP) + " * " + str(eP))
        print("= " + str(self.kP * eP))
        print("kI * eI = " + str(self.kI) + " * " + str(eI))
        print("= " + str(self.kI * eI))
        print("kD * eD = " + str(self.kD) + " * " + str(eD))
        print("= " + str(self.kD * eD) + "\n")
        print("OUTPUTS:")
        print("omega: " + str(omega))
        print("v    : " + str(v))
